#!/usr/bin/env bash
# Bump SemVer patch in VERSION (or set exact with: bump-version.sh 1.2.3)
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
vf="$root/VERSION"
cur="$(tr -d ' \r\n' <"$vf" 2>/dev/null || echo 0.1.0)"
if [[ -n "${1:-}" ]]; then
  next="$1"
else
  IFS=. read -r maj min pat <<<"$cur"
  next="${maj}.${min}.$((pat + 1))"
fi
printf '%s' "$next" >"$vf"
echo "VERSION $cur -> $next" >&2

python3 - "$root" "$next" <<'PY'
import json, pathlib, sys
root = pathlib.Path(sys.argv[1])
ver = sys.argv[2]
pkg = root / "web" / "package.json"
if pkg.exists():
    data = json.loads(pkg.read_text(encoding="utf-8"))
    data["version"] = ver
    pkg.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
gen = root / "web" / "src" / "generated"
gen.mkdir(parents=True, exist_ok=True)
(gen / "version.ts").write_text(
    "/** Auto-generated by scripts/bump-version.sh — do not edit. */\n"
    f"export const APP_VERSION = '{ver}'\n",
    encoding="utf-8",
)
print(ver)
PY
