<#
.SYNOPSIS
  Bump SemVer patch in VERSION (and sync web package + generated UI constant).

.PARAMETER Set
  Set exact version (x.y.z) instead of bumping patch.

.PARAMETER NoWriteGenerated
  Only update VERSION / package.json (skip web/src/generated/version.ts).
#>
param(
  [string]$Set = "",
  [switch]$NoWriteGenerated
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$versionFile = Join-Path $root "VERSION"

function Get-SemVer([string]$raw) {
  $v = ($raw -replace '[^\d.].*', '').Trim()
  if ($v -notmatch '^(\d+)\.(\d+)\.(\d+)$') {
    throw "Invalid SemVer in VERSION: '$raw' (want MAJOR.MINOR.PATCH)"
  }
  return [pscustomobject]@{
    Major = [int]$Matches[1]
    Minor = [int]$Matches[2]
    Patch = [int]$Matches[3]
    Text  = "$($Matches[1]).$($Matches[2]).$($Matches[3])"
  }
}

if (-not (Test-Path $versionFile)) {
  "0.1.0" | Set-Content -Path $versionFile -Encoding ascii -NoNewline
}

$current = Get-SemVer (Get-Content $versionFile -Raw)
if ($Set) {
  $next = (Get-SemVer $Set).Text
} else {
  $next = "{0}.{1}.{2}" -f $current.Major, $current.Minor, ($current.Patch + 1)
}

Set-Content -Path $versionFile -Value $next -Encoding ascii -NoNewline
Write-Host "VERSION $(($current).Text) -> $next"

$pkgPath = Join-Path $root "web\package.json"
if (Test-Path $pkgPath) {
  $raw = Get-Content $pkgPath -Raw
  $updated = [regex]::Replace($raw, '"version"\s*:\s*"[^"]*"',('"version": "{0}"' -f $next), 1)
  Set-Content -Path $pkgPath -Value $updated -Encoding utf8 -NoNewline
}

if (-not $NoWriteGenerated) {
  $genDir = Join-Path $root "web\src\generated"
  New-Item -ItemType Directory -Force -Path $genDir | Out-Null
  $ts = @"
/** Auto-generated by scripts/bump-version.ps1 — do not edit. */
export const APP_VERSION = '$next'
"@
  Set-Content -Path (Join-Path $genDir "version.ts") -Value $ts -Encoding utf8
}

# Return version for callers
Write-Output $next
